require("dotenv").config();

const mongoose = require("mongoose");
const Application = require("./models/Application");
const Company = require("./models/Company");
const InterviewRound = require("./models/InterviewRound");
const Student = require("./models/Student");

const MIN_STUDENTS = 800;
const MIN_COMPANIES = 80;
const MIN_APPLICATIONS = 4000;

const departments = [
  "CSE",
  "ISE",
  "AIML",
  "ECE",
  "EEE",
  "ME",
  "CIVIL",
];

const skills = [
  "Java",
  "Python",
  "React",
  "Node.js",
  "MongoDB",
  "SQL",
  "Data Structures",
  "Cloud",
  "Testing",
  "Analytics",
];

const companyNames = [
  "Infosys",
  "TCS",
  "Wipro",
  "Accenture",
  "Capgemini",
  "Cognizant",
  "Deloitte",
  "IBM",
  "Oracle",
  "SAP Labs",
  "Microsoft",
  "Amazon",
  "Google",
  "Adobe",
  "Cisco",
  "Salesforce",
  "Zoho",
  "Freshworks",
  "Paytm",
  "PhonePe",
  "Razorpay",
  "Flipkart",
  "Swiggy",
  "Zomato",
  "HCLTech",
  "Tech Mahindra",
  "LTIMindtree",
  "Bosch",
  "Siemens",
  "Mercedes Benz R&D",
  "Goldman Sachs",
  "JP Morgan Chase",
  "Morgan Stanley",
  "Wells Fargo",
  "Visa",
  "Mastercard",
  "Intuit",
  "Atlassian",
  "ServiceNow",
  "Workday",
  "Nutanix",
  "VMware",
  "Red Hat",
  "Dell Technologies",
  "HP Enterprise",
  "NVIDIA",
  "Intel",
  "Qualcomm",
  "Texas Instruments",
  "Samsung R&D",
  "Sony India",
  "Philips",
  "GE Digital",
  "Schneider Electric",
  "Honeywell",
  "ABB",
  "Target",
  "Walmart Global Tech",
  "Tesco Bengaluru",
  "Lowes India",
  "Myntra",
  "Meesho",
  "Ola",
  "Uber",
  "LinkedIn",
  "Twitter",
  "Airbnb",
  "Dropbox",
  "Stripe",
  "Twilio",
  "Databricks",
  "Snowflake",
  "MongoDB",
  "Postman",
  "HashedIn",
  "Publicis Sapient",
  "Thoughtworks",
  "Mphasis",
  "Persistent Systems",
  "Birlasoft",
  "KPIT",
  "Mindtree",
  "Hexaware",
  "Cyient",
  "L&T Technology Services",
  "Mu Sigma",
  "Tiger Analytics",
  "Fractal Analytics",
  "Quantiphi",
  "KPMG",
  "EY",
  "PwC",
  "Grant Thornton",
  "NoBroker",
  "Groww",
  "Zerodha",
  "Cred",
  "Upstox",
  "MakeMyTrip",
  "Cleartrip",
  "Urban Company",
  "Unacademy",
  "Byjus",
  "Scaler",
  "Tredence",
  "InMobi",
  "MoEngage",
  "BrowserStack",
];

const roundBlueprints = [
  { roundName: "Aptitude", roundType: "Aptitude", sequence: 1 },
  { roundName: "Coding", roundType: "Coding", sequence: 2 },
  { roundName: "Technical", roundType: "Technical", sequence: 3 },
  { roundName: "HR", roundType: "HR", sequence: 4 },
];

const statusDistribution = [
  { status: "Applied", weight: 10 },
  { status: "In Process", weight: 35 },
  { status: "Rejected", weight: 40 },
  { status: "Selected", weight: 12 },
  { status: "Offer Received", weight: 3 },
];

const randomInt = (min, max) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

const sample = (items) =>
  items[randomInt(0, items.length - 1)];

const shuffle = (items) =>
  [...items].sort(() => Math.random() - 0.5);

const pickStatus = () => {
  const total = statusDistribution.reduce(
    (sum, item) => sum + item.weight,
    0
  );
  let roll = Math.random() * total;

  for (const item of statusDistribution) {
    roll -= item.weight;

    if (roll <= 0) {
      return item.status;
    }
  }

  return "Applied";
};

const makeUsn = (index) =>
  `1RV21${sample(departments).padEnd(3, "X").slice(0, 3)}${String(
    index
  ).padStart(3, "0")}`;

const makeStudent = (index) => {
  const department = sample(departments);
  const selectedSkills = shuffle(skills).slice(0, randomInt(3, 6));

  return {
    usn: `1RV21${department.padEnd(3, "X").slice(0, 3)}${String(
      index
    ).padStart(3, "0")}`,
    name: `Student ${index}`,
    email: `student${index}@campustrack.edu`,
    phone: `9${String(100000000 + index).slice(0, 9)}`,
    department,
    cgpa: Number((6 + Math.random() * 3.8).toFixed(2)),
    graduationYear: 2026,
    skills: selectedSkills,
  };
};

const makeCompany = (index) => {
  const baseName = companyNames[index % companyNames.length];
  const packageValue = Number((4 + Math.random() * 24).toFixed(1));
  const driveDate = new Date();
  driveDate.setDate(driveDate.getDate() + randomInt(-30, 120));

  return {
    companyName: baseName,
    package: packageValue,
    location: sample(["Bengaluru", "Hyderabad", "Pune", "Chennai", "Remote"]),
    description: "Campus recruitment drive generated by seed data.",
    eligibilityCGPA: Number((6.5 + Math.random() * 2).toFixed(1)),
    minimumCGPA: Number((6.5 + Math.random() * 2).toFixed(1)),
    allowedDepartments: shuffle(departments).slice(0, randomInt(3, 5)),
    driveDate,
    status: driveDate < new Date() ? "Completed" : "Upcoming",
  };
};

const ensureStudents = async () => {
  const count = await Student.countDocuments();

  if (count >= MIN_STUDENTS) {
    return { inserted: 0, students: await Student.find() };
  }

  const existingStudents = await Student.find().select("usn email");
  const existingUsns = new Set(existingStudents.map((student) => student.usn));
  const existingEmails = new Set(existingStudents.map((student) => student.email));
  const studentsToCreate = [];
  let index = 1;

  while (count + studentsToCreate.length < MIN_STUDENTS) {
    const student = makeStudent(index);

    if (!existingUsns.has(student.usn) && !existingEmails.has(student.email)) {
      existingUsns.add(student.usn);
      existingEmails.add(student.email);
      studentsToCreate.push(student);
    }

    index += 1;
  }

  const inserted = await Student.insertMany(studentsToCreate, {
    ordered: false,
  });

  return {
    inserted: inserted.length,
    students: await Student.find(),
  };
};

const ensureCompanies = async () => {
  const count = await Company.countDocuments();

  if (count >= MIN_COMPANIES) {
    return { inserted: 0, companies: await Company.find() };
  }

  const existingCompanyNames = new Set(
    (await Company.find().select("companyName")).map(
      (company) => company.companyName
    )
  );
  const companiesToCreate = [];
  let index = 0;

  while (count + companiesToCreate.length < MIN_COMPANIES) {
    const company = makeCompany(index);

    if (!existingCompanyNames.has(company.companyName)) {
      existingCompanyNames.add(company.companyName);
      companiesToCreate.push(company);
    }

    index += 1;
  }

  const inserted = await Company.insertMany(companiesToCreate, {
    ordered: false,
  });

  return {
    inserted: inserted.length,
    companies: await Company.find(),
  };
};

const ensureRounds = async (companies) => {
  let created = 0;

  for (const company of companies) {
    const existingRounds = await InterviewRound.find({
      companyId: company._id,
    });
    const existingNames = new Set(
      existingRounds.map((round) => round.roundName)
    );
    const missingRounds = roundBlueprints
      .filter((round) => !existingNames.has(round.roundName))
      .map((round) => ({
        ...round,
        companyId: company._id,
      }));

    if (missingRounds.length) {
      const inserted = await InterviewRound.insertMany(missingRounds);
      created += inserted.length;
    }
  }

  return created;
};

const getRoundsByCompany = async () => {
  const rounds = await InterviewRound.find().sort({
    sequence: 1,
  });

  return rounds.reduce((map, round) => {
    const key = String(round.companyId);
    map[key] = map[key] || [];
    map[key].push(round);
    return map;
  }, {});
};

const buildRoundsForStatus = (status, rounds) => {
  if (!rounds?.length || status === "Applied") {
    return [];
  }

  if (status === "Selected" || status === "Offer Received") {
    return rounds.map((round) => ({
      roundId: round._id,
      attended: true,
      result: "PASS",
    }));
  }

  if (status === "Rejected") {
    const failIndex = randomInt(0, rounds.length - 1);
    return rounds.slice(0, failIndex + 1).map((round, index) => ({
      roundId: round._id,
      attended: true,
      result: index === failIndex ? "FAIL" : "PASS",
    }));
  }

  const completedRounds = randomInt(1, Math.max(1, rounds.length - 1));
  return rounds.slice(0, completedRounds).map((round) => ({
    roundId: round._id,
    attended: true,
    result: "PASS",
  }));
};

const currentRoundFor = (status, completedRounds, totalRounds) => {
  if (status === "Applied") {
    return 1;
  }

  if (status === "Rejected") {
    return Math.max(1, completedRounds);
  }

  if (status === "Selected" || status === "Offer Received") {
    return totalRounds + 1;
  }

  return Math.min(totalRounds, completedRounds + 1);
};

const ensureApplications = async (students, companies) => {
  const existingApplications = await Application.find().select(
    "studentId companyId status"
  );
  const existingPairs = new Set(
    existingApplications.map(
      (application) =>
        `${application.studentId}:${application.companyId}`
    )
  );

  if (existingApplications.length >= MIN_APPLICATIONS) {
    return {
      created: 0,
    };
  }

  const roundsByCompany = await getRoundsByCompany();
  const applicationsToCreate = [];

  for (const student of shuffle(students)) {
    const companyCount = randomInt(3, 8);
    const selectedCompanies = shuffle(companies).slice(0, companyCount);

    for (const company of selectedCompanies) {
      const pairKey = `${student._id}:${company._id}`;

      if (existingPairs.has(pairKey)) {
        continue;
      }

      const status = pickStatus();
      const companyRounds = roundsByCompany[String(company._id)] || [];
      const rounds = buildRoundsForStatus(status, companyRounds);
      const currentRound = currentRoundFor(
        status,
        rounds.length,
        companyRounds.length
      );

      existingPairs.add(pairKey);
      applicationsToCreate.push({
        studentId: student._id,
        companyId: company._id,
        currentRound,
        status,
        rounds,
      });
    }
  }

  let totalApplications =
    existingApplications.length +
    applicationsToCreate.length;

  if (totalApplications < MIN_APPLICATIONS) {
    for (const student of shuffle(students)) {
      for (const company of shuffle(companies)) {
        if (totalApplications >= MIN_APPLICATIONS) {
          break;
        }

        const pairKey = `${student._id}:${company._id}`;

        if (existingPairs.has(pairKey)) {
          continue;
        }

        const status = pickStatus();
        const companyRounds = roundsByCompany[String(company._id)] || [];
        const rounds = buildRoundsForStatus(status, companyRounds);
        const currentRound = currentRoundFor(
          status,
          rounds.length,
          companyRounds.length
        );

        existingPairs.add(pairKey);
        applicationsToCreate.push({
          studentId: student._id,
          companyId: company._id,
          currentRound,
          status,
          rounds,
        });
        totalApplications += 1;
      }

      if (totalApplications >= MIN_APPLICATIONS) {
        break;
      }
    }
  }

  if (!applicationsToCreate.length) {
    return { created: 0 };
  }

  const inserted = await Application.insertMany(applicationsToCreate, {
    ordered: false,
  });

  return {
    created: inserted.length,
  };
};

const printSummary = async ({
  studentsInserted,
  companiesInserted,
  roundsCreated,
  applicationsCreated,
}) => {
  const [selectedCount, rejectedCount, offerCount] = await Promise.all([
    Application.countDocuments({ status: "Selected" }),
    Application.countDocuments({ status: "Rejected" }),
    Application.countDocuments({ status: "Offer Received" }),
  ]);

  console.log("CampusTrack seed summary");
  console.log("------------------------");
  console.log(`Students inserted: ${studentsInserted}`);
  console.log(`Companies inserted: ${companiesInserted}`);
  console.log(`Rounds created: ${roundsCreated}`);
  console.log(`Applications created: ${applicationsCreated}`);
  console.log(`Selected count: ${selectedCount}`);
  console.log(`Rejected count: ${rejectedCount}`);
  console.log(`Offer count: ${offerCount}`);
};

const seed = async () => {
  if (!process.env.MONGO_URI) {
    throw new Error("MONGO_URI is missing in .env");
  }

  await mongoose.connect(process.env.MONGO_URI);

  const { inserted: studentsInserted, students } = await ensureStudents();
  const { inserted: companiesInserted, companies } = await ensureCompanies();
  const roundsCreated = await ensureRounds(companies);
  const { created: applicationsCreated } = await ensureApplications(
    students,
    companies
  );

  await printSummary({
    studentsInserted,
    companiesInserted,
    roundsCreated,
    applicationsCreated,
  });
};

seed()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
